project:
  type: website

website:

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: Blog-py
      - href: "https://mkolgesiz.github.io/blog-r/blog.html"
        text: Blog-r
    right:
      - icon: github
        href: https://github.com/mkolgesiz
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/mkolgesiz.bsky.social
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: 'https://www.linkedin.com/in/mkolgesiz'

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



